### ISSUE TITLE
warning: cast between incompatible function types

### ISSUE THREAD

**Issue by bjorn** [gjcarneiro/pybindgen#25]
With my version of g++ (9.2.1) I'm getting the following warning a lot (about 200 times for my bindings):
```
src/plugins/python/pythonbind.cpp:7211: warning: cast between incompatible function types from ‘PyObject* (*)(PyTiledMapObject*)’ {aka ‘_object* (*)(PyTiledMapObject*)’} to ‘PyCFunction’ {aka ‘_object* (*)(_object*, _object*)’} [-Wcast-function-type]
 7211 |     {(char *) "type", (PyCFunction) _wrap_PyTiledMapObject_type, METH_NOARGS, "type()\n\n" },
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I'm compiling with `-Wall -Wextra`, but not sure what's necessary to trigger this warning.

Of course I don't know if there's potential problems here, but it would be nice to not need to suppress this warning.

**Comment by gjcarneiro** [comment]
So, I don't have that compiler version here, so I'm a bit blind, but from what I could gather this new warning is due to PyCFunction signature always taking 3 parameters, but sometimes 1 or 2 of them are unused.

I fixed it by making sure these functions always take 3 parameters, even if some of them are unused.  Hopefully that fixes it.
