### ISSUE TITLE
Update the master development version according to the pygccxml master branch

### ISSUE THREAD

**Issue by sumagnadas** [gjcarneiro/pybindgen#35]
Recently the master branch of `pygccxml` was updated and ported to python3 so it might be helpful if the development version is at least updated according to it.

**Comment by sumagnadas** [comment]
@gjcarneiro `pygccxml` v2.0.0 has been released with support for `python 3.8` so please update the gccxml parser to include support for `python 3.8`

**Comment by sumagnadas** [comment]
Fixing #9 will be one of the things needed to port gccxml parser to python 3.8

**Comment by gjcarneiro** [comment]
Cool, to be honest pygccxml has been in such a sorry state for so long; perhaps time to test it again.  It used to be rather buggy in Python 3.

**Comment by sumagnadas** [comment]
oh and also, remove the gccxmlparser part because the dropped the support for gccxml and change the documentation to include tutorial for scanning header files using castxml parser

**Comment by gjcarneiro** [comment]
I tested with the `pybindgen.castxmlparser` module, and everything seems to work, so not sure what was meant by the initial comments in this bug?  Is it because you were using `pybindgen.gccxmlparser` and didn't notice the `pybindgen.castxmlparser` module that replaces it?

You're right the example needs updating.
